# The root filesystem is read-only: host keys live on /data, created once by
# photonvision-data-setup.service (/usr/lib/photonvision-os/data-setup).
HostKey /data/ssh/ssh_host_ed25519_key
HostKey /data/ssh/ssh_host_ecdsa_key
HostKey /data/ssh/ssh_host_rsa_key
