################################################################################
#
# tensorflow-lite
#
################################################################################

TENSORFLOW_LITE_VERSION = 2.11.0
TENSORFLOW_LITE_SITE =  $(call github,tensorflow,tensorflow,v$(TENSORFLOW_LITE_VERSION))
TENSORFLOW_LITE_INSTALL_STAGING = YES
TENSORFLOW_LITE_LICENSE = Apache-2.0
TENSORFLOW_LITE_LICENSE_FILES = LICENSE
TENSORFLOW_LITE_SUBDIR = tensorflow/lite
TENSORFLOW_LITE_SUPPORTS_IN_SOURCE_BUILD = NO
TENSORFLOW_LITE_DEPENDENCIES += \
	host-pkgconf \
	host-flatbuffers \
	cpuinfo \
	eigen \
	farmhash \
	fft2d \
	flatbuffers \
	gemmlowp \
	libabseil-cpp \
	neon-2-sse

TENSORFLOW_LITE_CONF_OPTS = \
	-Dabsl_DIR=$(STAGING_DIR)/usr/lib/cmake/absl \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) -I$(STAGING_DIR)/usr/include/gemmlowp" \
	-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON \
	-DCMAKE_POSITION_INDEPENDENT_CODE=ON \
	-DEigen3_DIR=$(STAGING_DIR)/usr/share/eigen3/cmake \
	-DFETCHCONTENT_FULLY_DISCONNECTED=ON \
	-DFETCHCONTENT_QUIET=OFF \
	-DFFT2D_SOURCE_DIR=$(STAGING_DIR)/usr/include/fft2d \
	-DFlatBuffers_DIR=$(STAGING_DIR)/usr/lib/cmake/flatbuffers \
	-DNEON_2_SSE_DIR=$(STAGING_DIR)/usr/lib/cmake/NEON_2_SSE \
	-DSYSTEM_FARMHASH=ON \
	-DTFLITE_ENABLE_EXTERNAL_DELEGATE=ON \
	-DTFLITE_ENABLE_GPU=OFF \
	-DTFLITE_ENABLE_INSTALL=ON \
	-DTFLITE_ENABLE_MMAP=ON \
	-DTFLITE_ENABLE_NNAPI=OFF

ifeq ($(BR2_PACKAGE_RUY),y)
TENSORFLOW_LITE_DEPENDENCIES += ruy
TENSORFLOW_LITE_CONF_OPTS += -DTFLITE_ENABLE_RUY=ON
else
TENSORFLOW_LITE_CONF_OPTS += -DTFLITE_ENABLE_RUY=OFF
endif

ifeq ($(BR2_PACKAGE_XNNPACK),y)
TENSORFLOW_LITE_DEPENDENCIES += xnnpack
TENSORFLOW_LITE_CONF_OPTS += -DTFLITE_ENABLE_XNNPACK=ON -Dxnnpack_POPULATED=ON
else
TENSORFLOW_LITE_CONF_OPTS += -DTFLITE_ENABLE_XNNPACK=OFF
endif

TENSORFLOW_LITE_C_API_SRCDIR = $(TENSORFLOW_LITE_DIR)/tensorflow/lite/c
TENSORFLOW_LITE_C_API_BUILDDIR = $(TENSORFLOW_LITE_DIR)/buildroot-build-c-api
TENSORFLOW_LITE_C_API_CONF_OPTS = $(TENSORFLOW_LITE_CONF_OPTS) -DTFLITE_C_BUILD_SHARED_LIBS=ON

define TENSORFLOW_LITE_BUILD_C_API
	(mkdir -p $(TENSORFLOW_LITE_C_API_BUILDDIR) && \
	cd $(TENSORFLOW_LITE_C_API_BUILDDIR) && \
	rm -f CMakeCache.txt && \
	PATH=$(BR_PATH) \
	$(if $(BR2_INSTALL_LIBSTDCPP),,CXX=/bin/false) \
	$(TENSORFLOW_LITE_CONF_ENV) $(BR2_CMAKE) $(TENSORFLOW_LITE_C_API_SRCDIR) \
		-G$(TENSORFLOW_LITE_GENERATOR) \
		-DCMAKE_MAKE_PROGRAM="$(TENSORFLOW_LITE_GENERATOR_PROGRAM)" \
		-DCMAKE_TOOLCHAIN_FILE="$(HOST_DIR)/share/buildroot/toolchainfile.cmake" \
		-DCMAKE_INSTALL_PREFIX="/usr" \
		-DCMAKE_INSTALL_RUNSTATEDIR="/run" \
		-DCMAKE_COLOR_MAKEFILE=OFF \
		-DBUILD_DOC=OFF \
		-DBUILD_DOCS=OFF \
		-DBUILD_EXAMPLE=OFF \
		-DBUILD_EXAMPLES=OFF \
		-DBUILD_TEST=OFF \
		-DBUILD_TESTS=OFF \
		-DBUILD_TESTING=OFF \
		-DBUILD_SHARED_LIBS=$(if $(BR2_STATIC_LIBS),OFF,ON) \
		$(CMAKE_QUIET) \
		$(TENSORFLOW_LITE_C_API_CONF_OPTS) \
	)
	$(TARGET_MAKE_ENV) $(TENSORFLOW_LITE_BUILD_ENV) $(BR2_CMAKE) --build $(TENSORFLOW_LITE_C_API_BUILDDIR) -j$(PARALLEL_JOBS) $(TENSORFLOW_LITE_BUILD_OPTS)
endef

define TENSORFLOW_LITE_INSTALL_C_API_STAGING
	$(INSTALL) -D -m 0644 $(TENSORFLOW_LITE_C_API_BUILDDIR)/libtensorflowlite_c.so $(STAGING_DIR)/usr/lib/libtensorflowlite_c.so
endef

define TENSORFLOW_LITE_INSTALL_C_API_TARGET
	$(INSTALL) -D -m 0644 $(TENSORFLOW_LITE_C_API_BUILDDIR)/libtensorflowlite_c.so $(TARGET_DIR)/usr/lib/libtensorflowlite_c.so
endef

TENSORFLOW_LITE_POST_BUILD_HOOKS += TENSORFLOW_LITE_BUILD_C_API
TENSORFLOW_LITE_POST_INSTALL_STAGING_HOOKS += TENSORFLOW_LITE_INSTALL_C_API_STAGING
TENSORFLOW_LITE_POST_INSTALL_TARGET_HOOKS += TENSORFLOW_LITE_INSTALL_C_API_TARGET

$(eval $(cmake-package))
