[buildroot]
repo = "https://github.com/buildroot/buildroot.git"
version = "2025.11"
defconfig = "raspberrypicm5io_defconfig"
external = ["gaia/assets/buildroot"]
compression = "none"
expand_size_mb = 2300
shrink_ext = true
collect_out_dir = "output/gaia/images"
archive_format = "img"
archive_mode = "image"
archive_name = "photonvision-helios-raze"
performance_profile = "max"
use_ccache = true
git_http_low_speed_limit = 1024
git_http_low_speed_time = 60
git_http_version = "HTTP/1.1"

[buildroot.rpi]
enabled = true
arch = "aarch64"
board = "cm5"
defconfig = "raspberrypicm5io_defconfig"
config_file = "gaia/assets/buildroot/config.txt"
cmdline_file = "gaia/assets/buildroot/cmdline.txt"

[buildroot.packages]
avahi = true
nss-mdns = true
libv4l = true
libv4l_utils = true
turbojpeg = true
linux-firmware = true
linux-firmware-rp2 = true
rpi_userland = true
openssl = true
openssh = true
bash = true
util-linux = true
e2fsprogs = true
python3 = true
openjdk = true
systemd = true
systemd_networkd = true
network-manager = true
net-tools = true
dnsmasq = true
libcamera = true
libcamera-apps = true
libdrm = true
libpisp = true
liburcu = true
libyuv = true
lttng_libust = true
numactl = true
elfutils = true
bzip2 = true
x264 = true
x265 = true
ffmpeg = true
libopenh264 = true
sqlite = true

[buildroot.symbols]
BR2_INIT_SYSTEMD = true
BR2_INIT_BUSYBOX = false
BR2_INIT_NONE = false
BR2_TARGET_GENERIC_HOSTNAME = "photonvision"
BR2_TARGET_GENERIC_ISSUE = "PhotonVision HeliOS Raze"
BR2_TARGET_ROOTFS_EXT2_LABEL = "ACTIVE"
BR2_TARGET_GENERIC_ROOT_PASSWD = "$$6$$1SRZhQNcL0XX7FM/$$NcrwlDSRGm0D7yD6SJ38PlpvB7vGvbj5Tvx9NWguLHuu2yva2bCPvb2Ec0z0McEZ.kWfGTglt6unXdevojnfB1"
BR2_ROOTFS_USERS_TABLES = "board/raspberrypicm5io/users.table"
BR2_LINUX_KERNEL_CUSTOM_TARBALL = true
BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION = "https://github.com/raspberrypi/linux/archive/refs/tags/stable_20250916.tar.gz"
BR2_PACKAGE_UTIL_LINUX_BINARIES = true
BR2_PACKAGE_E2FSPROGS_RESIZE2FS = true
BR2_PACKAGE_E2FSPROGS_E2FSCK = true
BR2_PACKAGE_E2FSPROGS_TUNE2FS = true
BR2_PACKAGE_E2FSPROGS_MKE2FS = true
BR2_PACKAGE_SQLITE_CLI = true
BR2_PACKAGE_LIGHTTPD_PCRE = true
BR2_PACKAGE_FFMPEG_GPL = true
BR2_PACKAGE_FFMPEG_SWSCALE = true
BR2_PACKAGE_FFMPEG_ENCODERS = "mjpeg libx264 libopenh264 libx265"
BR2_PACKAGE_FFMPEG_DECODERS = "mjpeg h264 h264_v4l2m2m hevc hevc_v4l2m2m"
BR2_PACKAGE_FFMPEG_PROTOCOLS = "file"
BR2_PACKAGE_FFMPEG_FILTERS = "scale"
BR2_PACKAGE_LIBCAMERA_V4L2 = true
BR2_PACKAGE_LIBCAMERA_PIPELINE_RPI_VC4 = true
BR2_PACKAGE_LIBCAMERA_PIPELINE_RPI_PISP = true
BR2_PACKAGE_LIBCAMERA_PIPELINE_UVCVIDEO = true
BR2_PACKAGE_LIBCAMERA_PIPELINE_VIMC = true
BR2_PACKAGE_LIBCAMERA_PIPELINE_SIMPLE = true
BR2_PACKAGE_HOST_DTC = true
